-- KAMAPIRO · configuración inicial de Supabase
-- 1) Pegá este archivo en Supabase > SQL Editor y ejecutalo.
-- 2) Luego creá un usuario de administración en Authentication > Users.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  category text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
to authenticated
using (true);

-- Bucket público para las fotos de productos.
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;

drop policy if exists "Authenticated users can upload product images" on storage.objects;
create policy "Authenticated users can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'products');

drop policy if exists "Authenticated users can update product images" on storage.objects;
create policy "Authenticated users can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'products')
with check (bucket_id = 'products');

drop policy if exists "Authenticated users can delete product images" on storage.objects;
create policy "Authenticated users can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'products');

-- El bucket es público para que la tienda pueda mostrar las imágenes.
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects for select
to public
using (bucket_id = 'products');

insert into public.products (name, code, category, price, stock, image_url)
values
('Cartera casual para dama','CAR-001','Carteras y bolsos',750,5,null),
('Perfume para dama','COS-002','Cosméticos',650,8,null),
('Set de maquillaje','COS-003','Cosméticos',480,6,null),
('Camiseta para caballero','HOM-004','Hombre',550,10,null),
('Blusa para dama','MUJ-005','Mujer',620,7,null),
('Tenis casuales','CAL-006','Calzado',1250,4,null),
('Reloj de caballero','ACC-007','Accesorios',900,5,null),
('Regalo decorativo','REG-008','Hogar y regalos',350,9,null)
on conflict (code) do nothing;
